name: UV Build

on:
  release:
    types: published

jobs:
  deploy:
    runs-on: [deabian-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install uv
        run: pip install uv

      - name: Cache uv dependencies
        id: cached-uv-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/requirements.txt') }}

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          uv pip install -e . # Install project in editable mode

      - name: Build Package
        run: |
          source .venv/bin/activate
          python -m build

      - name: Publish Build Package
        run: |
          source .venv/bin/activate
          python -m twine upload --repository pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
